package alireza:mypackage;

world myworld {
    record user-data {
        first-name: string,
        last-name: string,
        age: u32,
        grades: list<u32>,
    }

    export change-user: func(user1: user-data) -> user-data;
    export get-name: func(user1: user-data) -> string;
}