package alireza:mypackage;

world myworld {

    import host: interface {
      /// Example function that does a simple a × b operation
      multiply: func(a: f32, b: f32) -> f32;
      manual-get: func(url: string) -> option<string>;
      write-to-file: func(data: string, file-name: string);
      read-from-file: func(file-name: string) -> string;
    }
    export get-or-fetch: func(file-path: string, key: string, current-time: u64) -> option<string>;
}