// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
#include "myworld.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `myworld`

__attribute__((__weak__, __export_name__("cabi_post_to-string")))
void __wasm_export_exports_myworld_to_string_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + 4))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
  if ((*((size_t*) (arg0 + 12))) > 0) {
    free(*((uint8_t **) (arg0 + 8)));
  }
  size_t len = *((size_t*) (arg0 + 24));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 20));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 4;
      (void) base;
    }
    free(ptr);
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void myworld_list_u32_free(myworld_list_u32_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint32_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void myworld_user_data_free(myworld_user_data_t *ptr) {
  myworld_string_free(&ptr->first_name);
  myworld_string_free(&ptr->last_name);
  myworld_list_u32_free(&ptr->grades);
}

void myworld_string_set(myworld_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void myworld_string_dup(myworld_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void myworld_string_free(myworld_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[28];

__attribute__((__export_name__("to-string")))
uint8_t * __wasm_export_exports_myworld_to_string(uint8_t * arg, size_t arg0, uint8_t * arg1, size_t arg2, int32_t arg3, uint8_t * arg4, size_t arg5) {
  myworld_user_data_t arg6 = (myworld_user_data_t) {
    (myworld_string_t) (myworld_string_t) { (uint8_t*)(arg), (arg0) },
    (myworld_string_t) (myworld_string_t) { (uint8_t*)(arg1), (arg2) },
    (uint32_t) (uint32_t) (arg3),
    (myworld_list_u32_t) (myworld_list_u32_t) { (uint32_t*)(arg4), (arg5) },
  };
  myworld_user_data_t ret;
  exports_myworld_to_string(&arg6, &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + 4)) = ((ret).first_name).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) ((ret).first_name).ptr;
  *((size_t*)(ptr + 12)) = ((ret).last_name).len;
  *((uint8_t **)(ptr + 8)) = (uint8_t *) ((ret).last_name).ptr;
  *((int32_t*)(ptr + 16)) = (int32_t) ((ret).age);
  *((size_t*)(ptr + 24)) = ((ret).grades).len;
  *((uint8_t **)(ptr + 20)) = (uint8_t *) ((ret).grades).ptr;
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_myworld(void);
void __component_type_object_force_link_myworld_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_myworld();
}
