// Generated by `wit-bindgen` 0.39.0. DO NOT EDIT!
#ifndef __BINDINGS_MYWORLD_H
#define __BINDINGS_MYWORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct myworld_string_t {
  uint8_t*ptr;
  size_t len;
} myworld_string_t;

typedef struct {
  uint32_t *ptr;
  size_t len;
} myworld_list_u32_t;

typedef struct myworld_user_data_t {
  myworld_string_t   first_name;
  myworld_string_t   last_name;
  uint32_t   age;
  myworld_list_u32_t   grades;
} myworld_user_data_t;

// Exported Functions from `myworld`
void exports_myworld_to_string(myworld_user_data_t *user1, myworld_user_data_t *ret);

// Helper Functions

void myworld_list_u32_free(myworld_list_u32_t *ptr);

void myworld_user_data_free(myworld_user_data_t *ptr);

// Transfers ownership of `s` into the string `ret`
void myworld_string_set(myworld_string_t *ret, const char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void myworld_string_dup(myworld_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void myworld_string_free(myworld_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
